name: pfe22JOUINI_Ahmed
channels:
  -VS code notebooks
  -PyPI The Python Package Index
dependencies:
  -python=3.9.9
  -pip=21.2.4
  -pip:
    -numpy=1.21.0
    -sympy=1.10.1
    -OpenCV=4.5.5
    -numba=0.55.1
    -keras=2.5.0
    -tensorflow=2.5.0
    -PIL=9.1.0
    -pandas=1.4.2
    -sklearn=1.1.1
    -tensorflow_hub=0.12.0
    -matplotlib=3.5.1
    -csv=1.0